package io.github.loputevs.printtable.design;

import io.github.loputevs.printtable.Source;
import lombok.SneakyThrows;

import java.util.Comparator;
import java.util.Iterator;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.stream.Stream;

/**
 * ConfigNew level priority - properties are considered in the following order
 * <pre>
 * - default
 * - (in case then table generated from class) autogenerated
 * - table level
 * - column level
 * </pre>
 * if column level property is not provided take property value from table level or higher.
 *
 * @param <ROW_DATA>
 */
public class PrintTableNew<ROW_DATA> {
    
    /* FABRIC METHODS */
    
    public static <ROW_DATA> PrintTableNew<ROW_DATA> of(Iterable<ROW_DATA> rowSource) {
        // todo - wrap Source(rowSource)
        return null;
    }
    
    public static <ROW_DATA> PrintTableNew<ROW_DATA> of(Stream<ROW_DATA> rowSource) {
        // todo - wrap Source(rowSource)
        return null;
    }
    
    public static <KEY, VAL> PrintTableNew<Map.Entry<KEY, VAL>> of(Map<KEY, VAL> rowSource) {
        // todo - wrap Source(rowSource)
        return null;
    }
    
    public static <ROW_DATA> PrintTableNew<ROW_DATA> ofClassAutoGenerateColumns(Class<ROW_DATA> rowDataClass) {
        // todo - generateFromClass
        return null;
    }
    public static <ROW_DATA> PrintTableNew<ROW_DATA> ofClass(Class<ROW_DATA> rowDataClass) {
        // todo - PrintTable.of(String.class) // for add source later
        return null;
    }
    public static <ROW_DATA> PrintTableNew<ROW_DATA> of(Source<ROW_DATA> rowDataSource) {
        // todo - PrintTable.of(String.class) // for add source later
        return null;
    }
    
    
    /* INSTANCE METHODS */
    
    public PrintTableNew<ROW_DATA> config(ConfigNew configNew) {
        // todo - setConfig
        return this;
    }
    public PrintTableNew<ROW_DATA> source(Source<ROW_DATA> source) {
        // todo - impl
        return this;
    }
    
    /**
     * Reusing the method adds {@param filter} to the sort chain after
     * the last {@link Predicate} set.
     * <p>
     * {@param filter} will be called after the previous {@link Predicate}.
     */
    public PrintTableNew<ROW_DATA> filter(Predicate<ROW_DATA> predicate) {
        // TODO: 19.11.2024 impl
        return this;
    }
    
    /**
     * Repeated use of the method adds {@param comparator} to the sort chain after
     * the last {@link Comparator} set.
     * <p>
     * {@param comparator} will only be used if the previous
     * {@link Comparator} returned that both elements were equal.
     */
    public PrintTableNew<ROW_DATA> sort(Comparator<ROW_DATA> comparator) {
        // TODO: 19.11.2024 impl
        return this;
    }
  
    public <COLUMN_DATA> PrintTableNew<ROW_DATA> column(Column<ROW_DATA, COLUMN_DATA> column) {
        // TODO: 19.11.2024 impl
        return this;
    }
    public PrintTableNew<ROW_DATA> columnElementIndex() {
        // TODO: 19.11.2024 impl
        return this;
    }
    
    
    /* RESULT METHODS */
    
    public TableProcessResult toResult() {
        // TODO: 19.11.2024 impl
        return null;
    }
    public String toText() { // new ToTextProcessor(TableProcessResult)
        // TODO: 19.11.2024 impl
        return null;
    }
    public void print() {
        // TODO: 19.11.2024 impl
    }
    
    public Iterator<Object> toIterator() { // Iterator<Row>
        // TODO: 19.11.2024 impl
        return null;
    }
    public void toConsumer(Consumer<TableProcessResult> consumer) {
        consumer.accept(this.toResult());
    }
    @SneakyThrows
    public void toAppendable(Appendable appendable) {
        appendable.append(this.toText());
    }
    
    
    
}


